<strong>Module:</strong>        Album &raquo;
<strong>Controller:</strong>    Index &raquo;
<strong>Action:</strong>        add
<?php 
$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form->setAttribute('method', 'post');
$form->setAttribute('action', $this->url(Null, array('controller'=>'index', 'action' => 'add')));

$form->prepare();

 echo $this->form()->openTag($form);
 ?>
<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('name')); ?></dt>
<dd><?php 
    echo $this->formElement($form->get('name'));
    echo $this->formElementErrors($form->get('name'));
    
?></dd>
<dt><?php echo $this->formLabel($form->get('code')); ?></dt>
<dd><?php 
    echo $this->formElement($form->get('code'));
    echo $this->formElementErrors($form->get('code'));
 ?></dd>
 <dt><?php echo "</br>"; ?></dt>
<dd><?php 
    echo $this->formElement($form->get('submit'));
    echo $this->formElementErrors($form->get('submit'));
   
?></dd>
</dl>
<?php 
 echo $this->form()->closeTag();
?>