<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Album2\Module'                        => __DIR__ . '/Module.php',
    'Album2\Controller\IndexController' => __DIR__ . '/src/Album2/Controller/IndexController.php',
    'Album2Test\Framework\TestCase'        => __DIR__ . '/tests/Album2/Framework/TestCase.php',
    'Album2Test\SampleTest'                => __DIR__ . '/tests/Album2/SampleTest.php',
);
