<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Register\Module'                        => __DIR__ . '/Module.php',
    'Register\Controller\IndexController' => __DIR__ . '/src/Register/Controller/IndexController.php',
    'RegisterTest\Framework\TestCase'        => __DIR__ . '/tests/Register/Framework/TestCase.php',
    'RegisterTest\SampleTest'                => __DIR__ . '/tests/Register/SampleTest.php',
);
