<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Havij\Module'                        => __DIR__ . '/Module.php',
    'Havij\Controller\IndexController' => __DIR__ . '/src/Havij/Controller/IndexController.php',
    'HavijTest\Framework\TestCase'        => __DIR__ . '/tests/Havij/Framework/TestCase.php',
    'HavijTest\SampleTest'                => __DIR__ . '/tests/Havij/SampleTest.php',
);
