<strong>Module:</strong>        Havij &raquo;
<strong>Controller:</strong>    Index &raquo;
<strong>Action:</strong>        show
<?php 
//use Zend\Db\Adapter\Driver\ResultInterface;
//use Zend\Db\ResultSet\ResultSet;
//  $resultSet = new ResultSet;
    //$resultSet=$datatable;
//    $resultSet=$datatable;
//$resultSet->
//foreach ($datatable as $row) {
// echo    $row['alaki'];
//} 
?>
<table class="table">
<tr>
<th>Code</th>
<th>Artist</th>
<th>&nbsp;</th>
</tr>
<?php foreach ($datatable as $row) : ?>
<tr>
<td><?php echo $this->escapeHtml($row['code']);?></td>
<td><?php echo $this->escapeHtml($row['alaki']);?></td>
<td>
<a href="<?php //echo $this->url(’album’,
 //array(’action’=>’edit’, ’id’ => $album->id));?>">Edit</a>
 <a href="<?php //echo $this->url(’album’,
 //array(’action’=>’delete’, ’id’ => $album->id));?>">Delete</a>
 </td>
 </tr>
 <?php endforeach; ?>
 </table>
